# Generated by Django 5.1.1 on 2024-11-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcomp',
            name='numero_perdcomp_inicial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dcomp_inicial_docs', to='perdcomp.per'),
        ),
    ]
