# Generated by Django 5.1.1 on 2024-11-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomp', '0002_dcomp_numero_perdcomp_inicial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dcompdebitos',
            constraint=models.UniqueConstraint(fields=('numero_dcomp', 'grupo_tributo', 'codigo_da_receita_denominacao', 'periodo_da_apuracao'), name='unique_dcomp_debitos'),
        ),
    ]
