# Generated by Django 5.1.1 on 2024-11-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomp', '0003_dcompdebitos_unique_dcomp_debitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='per',
            name='credito_oriundo_de_acao_judicial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='per',
            name='credito_sucedido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='per',
            name='informado_em_outro_perdcomp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='per',
            name='informado_em_processo_admistrativo_anterior',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='per',
            name='pessoa_juridica_extinta_por_liquidacao_voluntaria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
