# Generated by Django 5.1.1 on 2024-11-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomp', '0004_alter_per_credito_oriundo_de_acao_judicial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='per',
            name='numero_perdcomp_retificador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
