# Generated by Django 5.1.1 on 2024-11-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomp', '0005_per_numero_perdcomp_retificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcomp',
            name='numero_perdcomp_retificador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
