# Generated by Django 5.1.1 on 2024-11-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomp', '0006_dcomp_numero_perdcomp_retificador'),
    ]

    operations = [
        migrations.AddField(
            model_name='per',
            name='csll_devida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='per',
            name='data_final_periodo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='per',
            name='data_inicial_periodo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='per',
            name='exercicio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='per',
            name='forma_apuracao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='per',
            name='forma_tributacao_lucro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='per',
            name='total_parcelas_composicao_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='per',
            name='valor_do_saldo_negativo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
