# Generated by Django 5.1.1 on 2024-11-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomp', '0007_per_csll_devida_per_data_final_periodo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='per',
            old_name='csll_devida',
            new_name='imposto_devido',
        ),
    ]
