# Generated by Django 5.1.1 on 2024-11-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomp', '0008_rename_csll_devida_per_imposto_devido'),
    ]

    operations = [
        migrations.AddField(
            model_name='per',
            name='periodo_de_apuracao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
