# Generated by Django 5.1.1 on 2024-11-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomp', '0009_per_periodo_de_apuracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcomp',
            name='data_final_periodo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcomp',
            name='data_inicial_periodo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcomp',
            name='exercicio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dcomp',
            name='forma_apuracao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dcomp',
            name='forma_tributacao_lucro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dcomp',
            name='imposto_devido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='dcomp',
            name='total_parcelas_composicao_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='dcomp',
            name='valor_saldo_negativo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
