# Generated by Django 5.1.1 on 2024-11-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomp', '0010_dcomp_data_final_periodo_dcomp_data_inicial_periodo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='per',
            name='periodo_de_apuracao',
        ),
        migrations.AlterField(
            model_name='dcomp',
            name='selic_acumulada',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
