# Generated by Django 5.1.1 on 2024-11-28 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomp', '0011_remove_per_periodo_de_apuracao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerCanc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_perdcomp', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_empresarial', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('data_transmissao', models.DateField(blank=True, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_credito', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_perdcomp_a_cancelar', models.CharField(blank=True, max_length=50, null=True)),
                ('credito_oriundo_de_acao_judicial', models.BooleanField(default=False)),
                ('pessoa_juridica_extinta_por_liquidacao_voluntaria', models.BooleanField(default=False)),
                ('nome_responsavel_da_pessoa_juridica_perante_rfb', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_do_responsavel_da_pessoa_juridica_perante_a_RFB', models.CharField(blank=True, max_length=20, null=True)),
                ('nome_responsavel_pelo_preechimento', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf_do_responsavel_pelo_preenchimento', models.CharField(blank=True, max_length=20, null=True)),
                ('dcomp_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelamentos_dcomp', to='perdcomp.dcomp')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canc_docs', to='perdcomp.empresa')),
                ('per_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelamentos_per', to='perdcomp.per')),
            ],
        ),
    ]
