# Generated by Django 5.1.1 on 2024-11-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomp', '0012_percanc'),
    ]

    operations = [
        migrations.AddField(
            model_name='percanc',
            name='versao_perdcomp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
