# Generated by Django 5.1.1 on 2024-11-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perdcomp', '0013_percanc_versao_perdcomp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percanc',
            name='numero_perdcomp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
