# Generated by Django 5.1.1 on 2024-10-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagemforum',
            name='descricao',
            field=models.TextField(max_length=500, verbose_name='Descrição'),
        ),
    ]
