# Generated by Django 5.1.1 on 2024-11-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_postagemforumimagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagemforum',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
