# Generated by Django 5.1.1 on 2024-11-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_postagemforum_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagemforum',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
