# Generated by Django 5.1.1 on 2024-11-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_postagemforumcomentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagemforumcomentario',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
    ]
